import client from "./client";
import {
  GET_ITEMS,
  SEARCH_ITEMS,
  GET_CART_ITEMS,
  GET_ITEMS_PRICE_ASC,
  GET_ITEMS_PRICE_DESC,
  GET_ITEMS_TITLE_ASC,
  GET_ITEMS_TITLE_DESC,
} from "./queries";

export {
  GET_ITEMS,
  SEARCH_ITEMS,
  GET_CART_ITEMS,
  GET_ITEMS_PRICE_ASC,
  GET_ITEMS_PRICE_DESC,
  GET_ITEMS_TITLE_ASC,
  GET_ITEMS_TITLE_DESC,
};
export default client;
