import client from "./client";
import {
  GET_ITEMS,
  SEARCH_ITEMS,
  GET_CART_ITEMS,
  GET_ITEMS_PRICE_ASC,
  GET_ITEMS_PRICE_DESC,
  GET_ITEMS_TITLE_ASC,
  GET_ITEMS_TITLE_DESC,
  GET_ONE_ITEM,
  GET_THREE_MORE_ITEMS,
  GET_COUPON,
  GET_ALL_COUPONS,
} from "./queries";

export {
  GET_COUPON,
  GET_ITEMS,
  SEARCH_ITEMS,
  GET_CART_ITEMS,
  GET_ITEMS_PRICE_ASC,
  GET_ITEMS_PRICE_DESC,
  GET_ITEMS_TITLE_ASC,
  GET_ITEMS_TITLE_DESC,
  GET_ONE_ITEM,
  GET_THREE_MORE_ITEMS,
  GET_ALL_COUPONS,
};

export default client;
